### ISSUE TITLE
[14133] DateChooser : l'attribut toolTipText n'est pas vocalisé par NVDA

### ISSUE THREAD

**Issue by Fabrice2** [Vedana/rcfaces-1.2#1]
L'attribut toolTipText du composant dateChooser génère bien un tooltip visible à l'écran, mais l'attribut 'title' est placée au mauvais endroit.

Il faudrait placé l'attribut 'title' dans le code généré sur la balise 'a' ou la balise 'img' à la place de la balise 'div' englobante pour que NVDA puisse vocaliser correctement le tooltip

**Comment by oeuillot** [comment]
Fixed https://github.com/Vedana/rcfaces-1.2/commit/eeb5e32770dc26bd8f6cbd75aef42920d39afc7c
