### ISSUE TITLE
[10980] Modification intempestive de la coloration des lignes dans un componentGrid

### ISSUE THREAD

**Issue by Fabrice2** [Vedana/rcfaces-1.2#2]
A l'affichage d'un componentGrid, lorsqu'une ligne est survolée une 1ere fois par la souris, elle change de couleur (blanc => gris ou gris => blanc); les survol suivants ne modifient plus sa coloration.

Il faut que le comportement du componentGrid soit similaire à celui du dataGrid, c'est à dire qu'il n'y ait aucun changement de couleur lors du survol d'une ligne

**Comment by oeuillot** [comment]
Fixed: https://github.com/Vedana/rcfaces-1.2/commit/9dd0fa0a3ddc768bc72720df3e9e54f61c89ddac
