### ISSUE TITLE
[14332] Arbo Dossier : Le noeud contenant le focus est toujours affiché tout en bas du cadre

### ISSUE THREAD

**Issue by Fabrice2** [Vedana/rcfaces-1.2#3]
Lorsque le focus est positionné avec setFocusArbo ou sur le dernier noeud cliqué, le noeud sur lequel le focus est positionné est toujours affiché en base du cadre, on voit uniquement le liseré bleu qui dépasse. (voir image)

Il faudrait afficher ce noeud en milieu de cadre.

![arboguso](https://cloud.githubusercontent.com/assets/7008829/6728832/44dad7d6-ce2d-11e4-8aac-5597671e622c.JPG)

**Comment by oeuillot** [comment]
Est-il possible d'appliquer le correctif sur le niveau 5 de l'arbre. 
Et vérifier que cela ne se produit plus lorsque la scrollbar en bas ne s'affiche pas !

**Comment by Fabrice2** [comment]
L'ascenseur horizontal apparaît à cause du code fonctionnel (positionne de width et height certainement). Le focus se porte en bas de cadre comme attendu et est bien affiché sans l'ascenseur horizontal.

Il faudrait préciser s'il y a un algo pour positionner le overflow: auto; à partir des valeurs de width et height)
