### ISSUE TITLE
[14331] Arbo dossier : Décalage dans l'affichage du 5ième niveau d'arborescence

### ISSUE THREAD

**Issue by Fabrice2** [Vedana/rcfaces-1.2#4]
Dans l'affichage de l'arbo dossier, le 5ieme niveau de profondeur n'est pas prévu en terme de css d'affichage. De ce fait les textes sont est trop décalés vers la droite.

La correction se situe dans rcfaces. il faut créer un nouveau style pe_tree_depth5  (vu avec Olivier)

**Comment by oeuillot** [comment]
rcface-pe problem !
