### ISSUE TITLE
[14653] Mauvais affichage des liens dans un dataGrid avec l'attribut allCellClickable="true"

### ISSUE THREAD

**Issue by Fabrice2** [Vedana/rcfaces-1.2#6]
Si on utilise l'attribut allCellClickable="true" dans un dataColumn , les soulignés du texte ne sont pas affichés lors du premier affichage de la page.

Après un passage de souris au dessus des lignes de la dataGrid, le souligné apparait de manière permanente.

**Comment by oeuillot** [comment]
Fixed: https://github.com/Vedana/rcfaces-1.2/commit/352b1da43b5b14959379f90150bdce65691e162e

**Comment by oeuillot** [comment]
Fixed for cellClickable='true' not for allCellClickable="true"
