### ISSUE TITLE
[21205] composant <p:scheduler> : Décalage des périodes du dimanche

### ISSUE THREAD

**Issue by Fabrice2** [Vedana/rcfaces-1.2#7]
Lorsqu'on positionne 7 colonnes dans la composant <p:scheduler>, les périodes existantes pour le 7ième jour (à savoir le dimanche) apparaissent en début de tableau (au dessus de la colonne des heures) et pas dans leur colonne.

**Comment by oeuillot** [comment]
Corrigé par

https://github.com/Vedana/rcfaces-1.2/commit/22a7311cb1fb6f5cab94c974e156ab3d7e8e12d3
