### ISSUE TITLE
[21886] Sélection d'un textEntry dans un componentsGrid impossible à la souris

### ISSUE THREAD

**Issue by Fabrice2** [Vedana/rcfaces-1.2#8]
Lorsqu'on clique avec la souris dans un textEntry situé dans un componentsGrid, le curseur se positionne directement en début ou fin de champ. Il est impossible de se placer au milieu du mot par exemple, ou bien de tout sélectionner avec un double-clic ou un triple-clic.

Cela fonctionne bien quand le textEntry est en dehors d'un componentsGrid

**Comment by oeuillot** [comment]
Corrigé par
https://github.com/Vedana/rcfaces-1.2/commit/120f99c66f87f338f236f2a70bc1d0c36d1dae79
