### ISSUE TITLE
[ 36055] L'ascenseur vertical ne suit pas le focus lorsqu'on utilise les flèches pour naviguer dans une comboBox

### ISSUE THREAD

**Issue by Fabrice2** [Vedana/rcfaces-1.2#9]
Dans une liste déroulante (comboBox), on peut utiliser les flèches haut/bas pour se déplacer dans la liste.
S'il y a un ascenseur vertical, on ne voit plus le focus sur la ligne sur laquelle on se déplace car l'ascenseur ne suit pas le mouvement des flèches et ne permet pas d'afficher les lignes suivantes dans la liste.

**Comment by oeuillot** [comment]
Corrigé par 
https://github.com/Vedana/rcfaces-1.2/commit/0a1b0583c84f953e0f0e4c27468fae3ac1814b04
